cmake_minimum_required(VERSION 3.18)

set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
if (APPLE)
    execute_process(COMMAND xcodebuild -version
        OUTPUT_VARIABLE XcodeOut)
    separate_arguments(XcodeParts UNIX_COMMAND ${XcodeOut})
    list(GET XcodeParts 1 XCODE_VER)
    if (${XCODE_VER} VERSION_GREATER_EQUAL "13.0")
	    set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
    else()
	    set(CMAKE_OSX_ARCHITECTURES "x86_64")
    endif()
    message("XCODE_VER=${XCODE_VER} CMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}")
	set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15" CACHE STRING "Minimum OS X deployment version")
endif()

project(scribeLibs)

if(HAIKU)
	set(LIBJPEG_SO "/boot/system/develop/lib/libjpeg.so")
	if (NOT EXISTS ${LIBJPEG_SO})
		message(FATAL_ERROR "No libjpeg at: ${LIBJPEG_SO}")
	endif()
	add_library(libjpeg SHARED IMPORTED)
	
elseif(NOT APPLE)
    if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/../../../codelib/libjpeg-9a")
        set(LIBJPEG ../../../codelib/libjpeg-9a)
    elseif (EXISTS "${CMAKE_CURRENT_LIST_DIR}/../../../codelib/libjpeg")
        set(LIBJPEG ../../../codelib/libjpeg)
    else()
        message(FATAL_ERROR "Can't find libjpeg")
    endif()
endif()

add_subdirectory(aspell-0.60.6.1)
add_subdirectory(libchardet)
add_subdirectory(libiconv-1.17)
#if (NOT TARGET libjpeg9a)
#    add_subdirectory(${LIBJPEG} libjpeg-9a)
#endif()
#if (NOT TARGET libpng16)
#    add_subdirectory(../../../codelib/libpng libpng)
#endif()

add_subdirectory(Btree)
add_subdirectory(bzip2-1.0.6)
