cmake_minimum_required(VERSION 3.18)

set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
if (APPLE)
	set(CMAKE_OSX_ARCHITECTURES "x86_64;ARM64")
	set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15" CACHE STRING "Minimum OS X deployment version")
endif()

project(scribeLibs)

if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/../../../codelib/libjpeg-9a")
    set(LIBJPEG ../../../codelib/libjpeg-9a)
elseif (EXISTS "${CMAKE_CURRENT_LIST_DIR}/../../../codelib/libjpeg")
    set(LIBJPEG ../../../codelib/libjpeg)
else()
    message(FATAL_ERROR "Can't find libjpeg")
endif()

add_subdirectory(aspell-0.60.6.1)
add_subdirectory(libchardet)
add_subdirectory(libiconv-1.17)
if (NOT TARGET libjpeg9a)
    add_subdirectory(${LIBJPEG} libjpeg-9a)
endif()
if (NOT TARGET libpng16)
    add_subdirectory(../../../codelib/libpng libpng)
endif()

add_subdirectory(Btree)
add_subdirectory(bzip2-1.0.6)